$("#slider").owlCarousel({
			items:1,
			stagePadding:30,
			smartSpeed:450,
			autoplay:true,
			autoWidth:true,
			loop:true
});
$("#sliderdesc").owlCarousel({
			items:1,
			stagePadding:30,
			smartSpeed:450,
			autoplay:true,
			autoWidth:true,
			loop:true
});